(cl:defpackage jace3373_hw1-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "SAYSOMETHING"
   "<SAYSOMETHING-REQUEST>"
   "SAYSOMETHING-REQUEST"
   "<SAYSOMETHING-RESPONSE>"
   "SAYSOMETHING-RESPONSE"
  ))

