// Generated by gencpp from file jace3373-hw1/AddTwoInts.msg
// DO NOT EDIT!


#ifndef JACE3373-HW1_MESSAGE_ADDTWOINTS_H
#define JACE3373-HW1_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <jace3373-hw1/AddTwoIntsRequest.h>
#include <jace3373-hw1/AddTwoIntsResponse.h>


namespace jace3373-hw1
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace jace3373-hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jace3373-hw1::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::jace3373-hw1::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::jace3373-hw1::AddTwoInts > {
  static const char* value()
  {
    return "jace3373-hw1/AddTwoInts";
  }

  static const char* value(const ::jace3373-hw1::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::jace3373-hw1::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::jace3373-hw1::AddTwoInts >
template<>
struct MD5Sum< ::jace3373-hw1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jace3373-hw1::AddTwoInts >::value();
  }
  static const char* value(const ::jace3373-hw1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jace3373-hw1::AddTwoIntsRequest> should match
// service_traits::DataType< ::jace3373-hw1::AddTwoInts >
template<>
struct DataType< ::jace3373-hw1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::jace3373-hw1::AddTwoInts >::value();
  }
  static const char* value(const ::jace3373-hw1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jace3373-hw1::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::jace3373-hw1::AddTwoInts >
template<>
struct MD5Sum< ::jace3373-hw1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jace3373-hw1::AddTwoInts >::value();
  }
  static const char* value(const ::jace3373-hw1::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jace3373-hw1::AddTwoIntsResponse> should match
// service_traits::DataType< ::jace3373-hw1::AddTwoInts >
template<>
struct DataType< ::jace3373-hw1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::jace3373-hw1::AddTwoInts >::value();
  }
  static const char* value(const ::jace3373-hw1::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JACE3373-HW1_MESSAGE_ADDTWOINTS_H
