// Generated by gencpp from file jace3373_hw1/SaySomethingResponse.msg
// DO NOT EDIT!


#ifndef JACE3373_HW1_MESSAGE_SAYSOMETHINGRESPONSE_H
#define JACE3373_HW1_MESSAGE_SAYSOMETHINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jace3373_hw1
{
template <class ContainerAllocator>
struct SaySomethingResponse_
{
  typedef SaySomethingResponse_<ContainerAllocator> Type;

  SaySomethingResponse_()
    : response()  {
    }
  SaySomethingResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaySomethingResponse_

typedef ::jace3373_hw1::SaySomethingResponse_<std::allocator<void> > SaySomethingResponse;

typedef boost::shared_ptr< ::jace3373_hw1::SaySomethingResponse > SaySomethingResponsePtr;
typedef boost::shared_ptr< ::jace3373_hw1::SaySomethingResponse const> SaySomethingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator1> & lhs, const ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator1> & lhs, const ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jace3373_hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jace3373_hw1/SaySomethingResponse";
  }

  static const char* value(const ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaySomethingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jace3373_hw1::SaySomethingResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JACE3373_HW1_MESSAGE_SAYSOMETHINGRESPONSE_H
